apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - job.yaml

configMapGenerator:
  - name: scale-down-script
    files:
      - run-scale.sh

generatorOptions:
  disableNameSuffixHash: true
