apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scale-deployments
subjects:
  - kind: ServiceAccount
    name: scaler
