apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: "fleet-aggregator"

# Pull every microservice manifest/base from its ADO Git repo
resources:
{{- range $svc := .Values.services }}
  - {{ include "ado.remote.url" (dict "svc" $svc "Values" $.Values) | quote }}
{{- end }}

# Apply replica patches across the aggregated set
patchesStrategicMerge:
  - patches/all-replicas.yaml
